[package]
name = "zuradio-desktop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lib]
name = "zuradio_desktop"
crate-type = ["lib", "cdylib", "staticlib"]

[[bin]]
name = "zuradio-desktop"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
tauri.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
url.workspace = true
zuradio-daemon = { path = "../../../crates/zuradio-daemon" }

[target.'cfg(target_os = "linux")'.dependencies]
webkit2gtk = "2.0.2"

[lints]
workspace = true
